dlive:
  # mix rack ip
  ip: 192.168.1.70

  # uses unencrypted traffic over port 51325 if 'use_auth' is disabled and
  # TLS/SSL over port 51327 if enabled
  use_auth: false
  user_profile: 0x00
  user_password: ''

  # see lower number of range selected in Utility/Control/MIDI (default: 12)
  midi_bank_offset: 12

streamdeck:
    devices:
      # device serials
      system: 'AL47J2C09831'
      input: 'CL15K1A02081'
      output: 'CL15K1A02084'

control:
  tracking:
    # number of inputs/aux busses/fx returns to track
    number_of_inputs: 96
    number_of_mono_aux: 8
    number_of_stereo_aux: 8
    number_of_mono_fx: 10
    number_of_stereo_fx: 0

    # first of 16 virtual input channels
    virtual_start: 101

    # feedback matrix channel
    feedback_matrix: 1

  scenes:
    # mixing bank 1..6
    mixing_start: 451

    # virtual channel banks 1..6 left and (single one) right
    outputs_left_start: 461
    outputs_right: 467

    # sends on fader/s-dca
    sends: 468

    # custom scenes
    custom_aux: 471
    custom_fx: 472
